/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CarType = IDL.Variant({ 'ev' : IDL.Null, 'petrol' : IDL.Null });
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CarId = IDL.Nat;
export const NewsArticleId = IDL.Nat;
export const Car = IDL.Record({
  'id' : CarId,
  'mileage' : IDL.Nat,
  'engineOrBatterySpecs' : IDL.Text,
  'cons' : IDL.Vec(IDL.Text),
  'expertReview' : IDL.Text,
  'name' : IDL.Text,
  'pros' : IDL.Vec(IDL.Text),
  'expectedLaunchDate' : Time,
  'exteriorFeatures' : IDL.Vec(IDL.Text),
  'isFeatured' : IDL.Bool,
  'safetyFeatures' : IDL.Vec(IDL.Text),
  'brand' : IDL.Text,
  'carType' : CarType,
  'topSpeed' : IDL.Nat,
  'interiorFeatures' : IDL.Vec(IDL.Text),
  'expectedPriceInr' : IDL.Nat,
  'range' : IDL.Nat,
  'isTrending' : IDL.Bool,
  'images' : IDL.Vec(ExternalBlob),
});
export const NewsArticle = IDL.Record({
  'id' : NewsArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Time,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const ComparisonResult = IDL.Record({ 'car1' : Car, 'car2' : Car });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminAddCar' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CarType,
        Time,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Bool,
        IDL.Bool,
      ],
      [CarId],
      [],
    ),
  'adminAddNews' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Vec(IDL.Text)],
      [NewsArticleId],
      [],
    ),
  'adminDeleteCar' : IDL.Func([CarId], [], []),
  'adminDeleteNews' : IDL.Func([NewsArticleId], [], []),
  'adminUpdateCar' : IDL.Func([Car], [], []),
  'adminUpdateNews' : IDL.Func([NewsArticle], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getArticle' : IDL.Func([NewsArticleId], [NewsArticle], ['query']),
  'getCar' : IDL.Func([CarId], [Car], ['query']),
  'getCarComparison' : IDL.Func([CarId, CarId], [ComparisonResult], ['query']),
  'getCarsByFilter' : IDL.Func(
      [
        IDL.Opt(CarType),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Car)],
      ['query'],
    ),
  'searchCars' : IDL.Func([IDL.Text], [IDL.Vec(Car)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CarType = IDL.Variant({ 'ev' : IDL.Null, 'petrol' : IDL.Null });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CarId = IDL.Nat;
  const NewsArticleId = IDL.Nat;
  const Car = IDL.Record({
    'id' : CarId,
    'mileage' : IDL.Nat,
    'engineOrBatterySpecs' : IDL.Text,
    'cons' : IDL.Vec(IDL.Text),
    'expertReview' : IDL.Text,
    'name' : IDL.Text,
    'pros' : IDL.Vec(IDL.Text),
    'expectedLaunchDate' : Time,
    'exteriorFeatures' : IDL.Vec(IDL.Text),
    'isFeatured' : IDL.Bool,
    'safetyFeatures' : IDL.Vec(IDL.Text),
    'brand' : IDL.Text,
    'carType' : CarType,
    'topSpeed' : IDL.Nat,
    'interiorFeatures' : IDL.Vec(IDL.Text),
    'expectedPriceInr' : IDL.Nat,
    'range' : IDL.Nat,
    'isTrending' : IDL.Bool,
    'images' : IDL.Vec(ExternalBlob),
  });
  const NewsArticle = IDL.Record({
    'id' : NewsArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Time,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const ComparisonResult = IDL.Record({ 'car1' : Car, 'car2' : Car });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminAddCar' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CarType,
          Time,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Bool,
          IDL.Bool,
        ],
        [CarId],
        [],
      ),
    'adminAddNews' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Vec(IDL.Text)],
        [NewsArticleId],
        [],
      ),
    'adminDeleteCar' : IDL.Func([CarId], [], []),
    'adminDeleteNews' : IDL.Func([NewsArticleId], [], []),
    'adminUpdateCar' : IDL.Func([Car], [], []),
    'adminUpdateNews' : IDL.Func([NewsArticle], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getArticle' : IDL.Func([NewsArticleId], [NewsArticle], ['query']),
    'getCar' : IDL.Func([CarId], [Car], ['query']),
    'getCarComparison' : IDL.Func(
        [CarId, CarId],
        [ComparisonResult],
        ['query'],
      ),
    'getCarsByFilter' : IDL.Func(
        [
          IDL.Opt(CarType),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Car)],
        ['query'],
      ),
    'searchCars' : IDL.Func([IDL.Text], [IDL.Vec(Car)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };