/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'id' : CarId,
  'mileage' : bigint,
  'engineOrBatterySpecs' : string,
  'cons' : Array<string>,
  'expertReview' : string,
  'name' : string,
  'pros' : Array<string>,
  'expectedLaunchDate' : Time,
  'exteriorFeatures' : Array<string>,
  'isFeatured' : boolean,
  'safetyFeatures' : Array<string>,
  'brand' : string,
  'carType' : CarType,
  'topSpeed' : bigint,
  'interiorFeatures' : Array<string>,
  'expectedPriceInr' : bigint,
  'range' : bigint,
  'isTrending' : boolean,
  'images' : Array<ExternalBlob>,
}
export type CarId = bigint;
export type CarType = { 'ev' : null } |
  { 'petrol' : null };
export interface ComparisonResult { 'car1' : Car, 'car2' : Car }
export type ExternalBlob = Uint8Array;
export interface NewsArticle {
  'id' : NewsArticleId,
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'publishedAt' : Time,
  'category' : string,
  'image' : ExternalBlob,
}
export type NewsArticleId = bigint;
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminAddCar' : ActorMethod<
    [
      string,
      string,
      CarType,
      Time,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      string,
      Array<ExternalBlob>,
      boolean,
      boolean,
    ],
    CarId
  >,
  'adminAddNews' : ActorMethod<
    [string, string, string, ExternalBlob, Array<string>],
    NewsArticleId
  >,
  'adminDeleteCar' : ActorMethod<[CarId], undefined>,
  'adminDeleteNews' : ActorMethod<[NewsArticleId], undefined>,
  'adminUpdateCar' : ActorMethod<[Car], undefined>,
  'adminUpdateNews' : ActorMethod<[NewsArticle], undefined>,
  'getAllArticles' : ActorMethod<[], Array<NewsArticle>>,
  'getAllCars' : ActorMethod<[], Array<Car>>,
  'getArticle' : ActorMethod<[NewsArticleId], NewsArticle>,
  'getCar' : ActorMethod<[CarId], Car>,
  'getCarComparison' : ActorMethod<[CarId, CarId], ComparisonResult>,
  'getCarsByFilter' : ActorMethod<
    [
      [] | [CarType],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [bigint],
    ],
    Array<Car>
  >,
  'searchCars' : ActorMethod<[string], Array<Car>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];